version: '3'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/pipeline
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: ["/usr/local/bin/test-entrypoint.sh"]
