name: Nextflow Pipeline Tests

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run nf-test suite
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Nextflow
        run: |
          wget -qO- https://get.nextflow.io | bash
          chmod +x nextflow
          sudo mv nextflow /usr/local/bin/

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip fastqc curl
          python3 -m pip install --upgrade pip
          
      # Only install the function test requirements
      - name: Install function test requirements
        run: |
          # Create a test reads directory
          mkdir -p test-data

      - name: Install fastp
        run: |
          wget http://opengene.org/fastp/fastp
          chmod a+x ./fastp
          sudo mv ./fastp /usr/local/bin/

      - name: Run function tests
        run: |
          nextflow run tests/functions/function_test.nf

      # For now, we'll focus on function tests, but later we can expand to use nf-test
      - name: Document test structure for future nf-test integration
        run: |
          echo "Tests that will be integrated with nf-test in the future:"
          find tests -type f -name "*.nf.test" | sort || echo "No .nf.test files found"

      # Additional validation steps
      - name: Verify pipeline structure
        run: |
          # Display module structure
          find modules -type f -name "*.nf" | sort
          
          # Display test structure
          find tests -type f -name "*.nf.test" -o -name "function_test.nf" | sort
