name: Nextflow Pipeline Tests

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run nf-test suite
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Nextflow
        run: |
          wget -qO- https://get.nextflow.io | bash
          chmod +x nextflow
          sudo mv nextflow /usr/local/bin/

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip fastqc curl
          python3 -m pip install --upgrade pip
          
      # Install nf-test using the exact version from GitHub without using the installer script
      - name: Install nf-test
        run: |
          wget -q https://github.com/nextflow-io/nf-test/releases/download/v0.8.4/nf-test-0.8.4-all.jar
          mkdir -p $HOME/.nf-test/bin
          echo '#!/bin/sh\njava -jar '$HOME'/.nf-test/bin/nf-test.jar "$@"' > $HOME/.nf-test/bin/nf-test
          cp nf-test-0.8.4-all.jar $HOME/.nf-test/bin/nf-test.jar
          chmod +x $HOME/.nf-test/bin/nf-test
          export PATH="$HOME/.nf-test/bin:$PATH"
          echo "$HOME/.nf-test/bin" >> $GITHUB_PATH
          echo "nf-test installation location:"
          ls -la $HOME/.nf-test/bin
          $HOME/.nf-test/bin/nf-test --version || echo "Could not determine version"

      - name: Install fastp
        run: |
          wget http://opengene.org/fastp/fastp
          chmod a+x ./fastp
          sudo mv ./fastp /usr/local/bin/

      - name: Run function tests
        run: |
          nextflow run tests/functions/function_test.nf

      - name: Run nf-test
        run: |
          # Make sure nf-test is in the PATH
          export PATH="$HOME/.nf-test/bin:$PATH"
          
          # Directly use the wrapper script we created
          echo "Running nf-test version:"
          $HOME/.nf-test/bin/nf-test --version || echo "Could not determine version"
          
          # Run the tests
          $HOME/.nf-test/bin/nf-test test --debug

      # Additional validation steps
      - name: Verify pipeline structure
        run: |
          # Display module structure
          find modules -type f -name "*.nf" | sort
          
          # Display test structure
          find tests -type f -name "*.nf.test" -o -name "function_test.nf" | sort
