name: Nextflow Pipeline Tests

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run nf-test suite
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Nextflow
        run: |
          wget -qO- https://get.nextflow.io | bash
          chmod +x nextflow
          sudo mv nextflow /usr/local/bin/

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip fastqc cargo
          python3 -m pip install --upgrade pip
          
      - name: Install nf-test
        run: |
          mkdir -p ~/bin
          wget -q https://github.com/askimed/nf-test/releases/download/v0.9.2/nf-test-linux-x86_64.tar.gz
          tar zxf nf-test-linux-x86_64.tar.gz
          chmod +x nf-test
          mv nf-test ~/bin/
          echo "$HOME/bin" >> $GITHUB_PATH
          export PATH="$HOME/bin:$PATH"
          echo "nf-test installation location: $(which nf-test || echo 'not found')"
          ls -la ~/bin
          
      - name: Install fastq-generator
        run: |
          cargo install fastq-generator

      - name: Install fastp
        run: |
          wget http://opengene.org/fastp/fastp
          chmod a+x ./fastp
          sudo mv ./fastp /usr/local/bin/

      - name: Run function tests
        run: |
          nextflow run tests/functions/function_test.nf

      - name: Run nf-test
        run: |
          export PATH="$HOME/bin:$PATH"
          echo "Running nf-test from: $(which nf-test || echo 'not found')"
          ~/bin/nf-test test --profile=test

      # Simple logging of test results instead of using potentially incompatible actions
      - name: Log test results
        if: always()
        run: |
          echo "Test execution completed"
          if [ -d ".nf-test/test-reports" ]; then
            echo "Test reports found. Summary:"
            find .nf-test/test-reports -name "*.xml" -exec grep -l "<testsuite" {} \; | xargs cat | grep -E 'failures="[^0]|errors="[^0]' || echo "All tests passed"
          else
            echo "No test reports found"
          fi
